<?php
$langArray = array(
    'big_file' => '!حجم الملف كبير',
    'upload_err' => '!حدث خطأ أثناء رفع الملف',
    'type_err' => '!لا يمكنك رفع ملف بهذه الصيغة',
    'success_uploads' => 'تم رفع الملف بنجاح',
    'single_file_err' => 'تستطيع اختيار ملف واحد فقط',

    // navbar links
    'Home'              => 'الرئيسية',
    'Categories'        => 'الفئات',
    'Items'             => 'المنتجات',
    'Profile Settings'  => 'إعدادات الحساب',
    'Logout'            => 'تسجيل الخروج',
    'Sign-in'           => 'تسجيل الدخول',
    'Sign-up'           => 'إنشاء حساب',
    'My Profile'        => 'حسابي',
    'Reset password'    => 'إعادة تعيين كلمة المرور',
    'Wish List'         => 'قائمة الرغبات',

    // Categories
    'Pet Supplies'      => 'لوازم الحيوانات الأليفة',
    'Office Supplies'   => 'لوازم المكتبة',
    'Travel'            => 'السفر',
    'Kitchen Appliances' => 'أجهزة المطبخ',
    'Computers'         => 'أجهزة الكمبيوتر',
    'Video Games'       => 'ألعاب الفيديو',
    'Smart Phones'      => 'الهواتف الذكية',
    'Books'             => 'كتب',
    'Automotive'        => 'سيارات',
    'Toys & Games'      => 'الألعاب',
    'Health & Beauty'   => 'الصحة والجمال',
    'Sports'            => 'الرياضة',
    'Home & Garden'     => 'المنزل والحديقة',
    'Fashion'           => 'موضة',
    'Electronics'       => 'إلكترونيات',

    // index.php
    'Welcome to ClickCart' => 'مرحبا بكم في ClickCart',
    'Your one-stop shop for the best items online. Enjoy our wide selection and fast shipping!' => 'متجرك الشامل لأفضل العناصر عبر الإنترنت. استمتع باختيارنا الواسع والشحن السريع!',
    'Shop now' => 'تسوق الآن',
    'Trending Items' => 'العناصر الشائعة',
    'Check out our trending items: PS5, iPhone 16, S24 Ultra, and more!' => 'تحقق من العناصر الشائعة لدينا: PS5، آيفون 16، S24 ألترا، والمزيد!',
    'Play more<br>today and get' => 'العب أكثر<br>اليوم واحصل على',
    'OFF' => 'خصم',
    'Use code %s to get %s off on Video Games category now' => 'استخدم الرمز %s للحصول على خصم %s في فئة ألعاب الفيديو الآن',
    'Previous' => 'السابق',
    'Next' => 'التالي',
    'Best Sellers' => 'الأكثر مبيعاً',
    'Most Viewed Items' => 'أكثر العناصر مشاهدة',
    'views' => 'مشاهدة',

    // items.php
    'results' => 'نتائج',
    'sort_by' => ':ترتيب حسب',
    'featured' => 'الأبرز',
    'price_low_high' => 'السعر: من الأقل إلى الأعلى',
    'price_high_low' => 'السعر: من الأعلى إلى الأقل',
    'newest_arrivals' => 'أحدث الإضافات',
    'most_viewed' => 'الأكثر مشاهدة',
    'best_sellers' => 'الأكثر مبيعاً',
    'previous' => 'السابق',
    'next' => 'التالي',
    'first' => 'الأول',
    'last' => 'الأخير',
    'item_added_cart' => '!تمت إضافة العنصر إلى السلة بنجاح',
    'item_already_cart' => '.العنصر موجود بالفعل في سلتك',
    'item_not_found' => '.لم يتم العثور على العنصر',
    'not_signed_in' => '.أنت غير مسجل الدخول لإضافة إلى السلة',
    'not_signed_in-comment' => '.أنت غير مسجل الدخول لإضافة تعليف',
    'comment_submitted' => 'تم إرسال تعليقك!',
    'comment_empty' => '!لا يمكن أن يكون التعليق فارغًا',
    'item_in_wishlist' => '!هذا العنصر موجود بالفعل في قائمة الرغبات الخاصة بك',
    'item_added_wishlist' => '!تمت إضافة العنصر إلى قائمة الرغبات الخاصة بك',
    'verified_buyer' => '!يجب أن تكون مشتريًا موثوقًا لترك مراجعة',
    'delete_item_failed' => 'لم يتمكن من حذف العنصر.',
    'no-items' => 'لا يوجد منتجات لعرضها',
    'non-approved' => '!هذا المنتج لم يتم الموفقة عليه بعد',
    'Product_by' => 'منتج من',
    'Average_Rate' => 'متوسط التقييم',
    'Based_on' => 'بناء على',
    'Ratings' => 'تقييم',
    'customer_reviews' => 'آراء العملاء',
    '*includes_tax' => 'مع الضريبة*',
    'Product_Description' => 'وصف المنتج',
    'Specifications' => 'خصائص',
    'Reviews' => 'التعليقات',
    'Description' => 'الوصف',
    'Write_a_review' => 'اترك رأيك عن المنتج هنا',
    'Rate_this_Item:' => ':قيم المنتج',
    '1star' => 'نجمة واحدة',
    '2star' => 'نجمتان',
    '3star' => 'نجوم 3',
    '4star' => 'نجوم 4',
    '5star' => 'نجوم 5',
    'Submit_Review' => 'إرسال المراجعة',
    'posted' => 'تم النشر',
    'No_comments_available' => 'لا يوجد تعليقات',
    'Add_to_cart' => 'أضف للعربة',
    'Add_to_wishlist' => 'أضف لقائمة الرغبات',
    'Contact_Seller' => 'تواصل مع البائع',
    'no-quantity' => 'نفذت الكمية',

    // login.php
    'welcome_back' => 'مرحباً مجدداً',
    'login' => 'تسجيل الدخول',
    'email_placeholder' => 'البريد الإلكتروني',
    'email_error_empty' => 'لا يمكن أن يكون البريد الإلكتروني فارغاً.',
    'email_error_invalid' => 'تنسيق البريد الإلكتروني غير صالح.',
    'password_placeholder' => 'كلمة المرور',
    'password_error_empty' => 'لا يمكن أن تكون كلمة المرور فارغة.',
    'remember_me' => 'تذكرني',
    'login_button' => 'تسجيل الدخول',
    'google_login' => 'متابعة باستخدام Google',
    'forgot_password' => 'نسيت كلمة المرور؟',
    'no_account' => 'ليس لديك حساب؟',
    'sign_up' => 'إنشاء حساب',
    'no_account_with_email' => 'لا يوجد حساب بهذا البريد الإلكتروني.',
    'incorrect_password' => 'كلمة المرور غير صحيحة.',

    // register.php
    'signup' => 'إنشاء حساب',
    'welcome' => 'مرحباً',
    'first_name' => 'الاسم الأول',
    'last_name' => 'الاسم الأخير',
    'password' => 'كلمة المرور',
    'email' => 'البريد الإلكتروني',
    'have_account' => 'لديك حساب؟',
    'login' => 'تسجيل الدخول',
    'register_button' => 'تسجيل',
    'cant_be_empty' => 'لا يمكن أن يكون فارغًا',
    'email_exists' => 'البريد الإلكتروني الذي أدخلته موجود بالفعل!',
    'password_error' => 'تنسيق كلمة المرور غير صالح.',
    'otp_error' => 'فشل أثناء إرسال الرمز!',
    'db_error' => 'حدث خطأ ما!',
    'otp_sent' => 'لقد أرسلنا رمز التحقق إلى بريدك الإلكتروني - ',

    // forgetPass.php
    'password_reset' => 'إعادة تعيين كلمة المرور',
    'password_reset_code' => 'رمز إعادة تعيين كلمة المرور',
    'password_reset_body' => 'رمز إعادة تعيين كلمة المرور الخاص بك هو:',
    'otp_sent' => 'لقد أرسلنا رمز إعادة تعيين كلمة المرور إلى بريدك الإلكتروني',
    'mail_error' => 'تعذر إرسال الرسالة. خطأ في البريد',
    'something_went_wrong' => 'حدث خطأ ما!',
    'email_not_exist' => 'عنوان البريد الإلكتروني هذا غير موجود!',
    'password_reset_instructions' => 'يرجى تقديم عنوان البريد الإلكتروني المرتبط بحسابك لاستعادة كلمة المرور الخاصة بك.',
    'reset_password_button' => 'إعادة تعيين كلمة المرور',
    'email' => 'البريد الإلكتروني',
    'login' => 'تسجيل الدخول',
    'register' => 'التسجيل',

    // reset-code.php
    'code_verification' => 'تأكيد الرمز',
    'no_email_session' => 'يرجى تسجيل الدخول أولاً.',
    'create_new_password_info' => 'يرجى إنشاء كلمة مرور جديدة لا تستخدمها في أي موقع آخر.',
    'incorrect_code' => 'لقد أدخلت رمزًا غير صحيح!',
    'email_verification_code' => 'رمز التحقق من البريد الإلكتروني',
    'new_code' => 'رمز التحقق الجديد هو:',
    'new_verification_code_sent' => 'تم إرسال رمز التحقق الجديد إلى بريدك الإلكتروني.',
    'failed_to_send_new_code' => 'فشل إرسال الرمز الجديد!',
    'failed_to_update_code' => 'فشل تحديث الرمز في قاعدة البيانات!',
    'verify' => 'تحقق',
    'code_sent' => 'تم إرسال الرمز إلى بريدك الإلكتروني',
    'did_not_receive_code' => 'لم تستلم الرمز؟ اطلبه مجددًا',
    'verify_button' => 'تحقق',

    // new-password.php
    'reset_password' => 'إعادة تعيين كلمة المرور',
    'cannot_be_empty' => 'لا يمكن أن يكون فارغًا',
    'passwords_not_matching' => 'كلمة المرور المؤكدة لا تتطابق!',
    'password_changed' => 'تم تغيير كلمة المرور الخاصة بك.',
    'strong_password_info' => 'تتضمن كلمات المرور القوية أرقامًا وحروفًا وعلامات ترقيم.',
    'new_password_info' => 'تم تغيير كلمة المرور الخاصة بك. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.',
    'reset_password_button' => 'إعادة تعيين كلمة المرور',
    'reset_password_header' => 'أعد تعيين كلمة المرور الخاصة بك',
    'password_placeholder' => 'أدخل كلمة مرور',
    'confirm_password_placeholder' => 'تأكيد كلمة المرور الجديدة',
    'db_error' => 'فشل في تغيير كلمة المرور الخاصة بك!',

    // user-otp.php
    'pageTitle' => 'رمز التحقق',
    'redirectToLogin' => 'الرجاء تسجيل الدخول.',
    'otpInstructions' => 'تم إرسال الرمز إلى بريدك الإلكتروني',
    'otpIncorrect' => 'لقد أدخلت رمزًا غير صحيح!',
    'otpErrorUpdate' => 'فشل أثناء تحديث الرمز!',
    'otpErrorResend' => 'فشل أثناء إرسال الرمز الجديد!',
    'otpResent' => 'تم إرسال رمز التحقق الجديد إلى بريدك الإلكتروني.',
    'otpUpdatedSuccess' => 'تم التسجيل بنجاح!',
    'verify' => 'تحقق',
    'verifyPrompt' => 'تم إرسال الرمز إلى بريدك الإلكتروني',
    'verifyButton' => 'تحقق',
    'resend' => 'لم تستلم الرمز؟ اطلب مرة أخرى',

    // newAd.php (Add section)
    'New Ad' => 'إعلان جديد',
    'Product already exists' => 'المنتج موجود بالفعل',
    'Price cannot be less than 0.99' => 'السعر لا يمكن أن يكون أقل من 0.99',
    'Quantity cannot be less than 1' => 'الكمية لا يمكن أن تكون أقل من 1',
    'Select the item status' => 'اختر حالة العنصر',
    'Select a category' => 'اختر الفئة',
    'Add New Product' => 'إضافة منتج جديد',
    'Product Picture' => 'صورة المنتج',
    'JPG or PNG, max size 5 MB' => 'JPG أو PNG، الحجم الأقصى 5 ميجابايت',
    'Upload' => 'تحميل',
    'Product Details' => 'تفاصيل المنتج',
    'Product added successfully' => 'تمت إضافة المنتج بنجاح انتظر الموافقة',
    'No changes were made' => 'لم يتم إجراء أي تغييرات',
    'Product Name' => 'اسم المنتج',
    'Name of The Item' => 'اسم العنصر',
    'Selling Price' => 'سعر البيع',
    'Price of The Item' => 'سعر العنصر',
    'Country Made' => 'بلد الصنع',
    'Country of Origin' => 'بلد المنشأ',
    'Quantity' => 'الكمية',
    'Quantity of The Item' => 'كمية العنصر',
    'Product Status' => 'حالة المنتج',
    'Select Product Status' => 'اختر حالة المنتج',
    'New' => 'جديد',
    'Like New' => 'مثل جديد',
    'Used' => 'مستخدم',
    'Very Old' => 'قديم جدا',
    'Category' => 'الفئة',
    'Select Category' => 'اختر الفئة',
    'Description' => 'الوصف',
    'Description of The Item' => 'وصف العنصر',
    'Add Item' => 'إضافة عنصر',
    'Primary Image' => 'الصورة الأساسية',
    'Additional Image 1' => 'صورة اضافية 1',
    'Additional Image 2' => 'صورة اضافية 2',

    // newAd.php (Edit section)
    'Edit Product' => 'تعديل المنتج الخاص بك',
    'Edit Item' => 'تعديل المنتج',
    'delete-item' => 'حذف المنتج',
    'Product Updated successfully' => 'تم تعديل منتجك بنجاح انتظر الموافقة',
    'Are you sure to delete?' => 'هل انت متأكد من حذف المنتج؟',
    'success_delete' => 'تم حذف المنتج بنجاح',
    'item_not_provided' => 'لم يتم ارفاق Item ID',

    // profile-settings.php
    'profile' => 'الملف الشخصي',
    'orders' => 'الطلبات',
    'wishlist' => 'قائمة الرغبات',
    'personal_info' => 'معلومات شخصية',
    'profile_picture' => 'صورة الملف الشخصي',
    'picture_info' => 'JPG أو PNG بحد أقصى 5 ميجابايت',
    'upload' => 'تحميل',
    'account_details' => 'تفاصيل الحساب',
    'first_name' => 'الاسم الأول',
    'enter_first_name' => 'أدخل الاسم الأول',
    'last_name' => 'الاسم الأخير',
    'enter_last_name' => 'أدخل الاسم الأخير',
    'location' => 'الموقع',
    'enter_location' => 'أدخل الموقع',
    'gender' => 'الجنس',
    'select_gender' => 'اختر جنسك',
    'male' => 'ذكر',
    'female' => 'أنثى',
    'email_address' => 'البريد الإلكتروني',
    'enter_email' => 'أدخل بريدك الالكتروني',
    'phone' => 'رقم الهاتف',
    'enter_phone' => 'أدخل رقم الهاتف',
    'birthday' => 'تاريخ الميلاد',
    'enter_birthday' => 'أدخل تاريخ الميلاد',
    'save_changes' => 'حفظ التغييرات',
    'success_update' => 'تم تحديث العضو بنجاح!',
    'warning_no_changes' => 'لم يتم إجراء أي تغييرات. لم يتم تحديث أي سجل.',

    // info section
    "Profile" => "الملف الشخصي",
    "Orders" => "الطلبات",
    "Wishlist" => "قائمة الرغبات",
    "Personal Info" => "المعلومات الشخصية",
    "My Profile" => "ملفي الشخصي",
    "My Ads" => "إعلاناتي",
    "New Ad?" => "إعلان جديد؟",
    "Approved" => "موافق عليه",
    "Waiting Approval" => "في انتظار الموافقة",
    "No Ads to Show. Create" => "لا توجد إعلانات لعرضها. أنشئ",
    "New Ad" => "إعلان جديد",
    "My Latest Comments" => "أحدث تعليقاتي",
    "Commented on:" => "تم التعليق في:",
    "Item:" => "المنتج:",
    "No comments to show." => "لا توجد تعليقات لعرضها.",
    'edit-item' => 'تعديل المنتج',

    // orders section
    "Profile" => "الملف الشخصي",
    "Orders" => "الطلبات",
    "Wishlist" => "قائمة الرغبات",
    "Personal Info" => "المعلومات الشخصية",
    "Order history" => "سجل الطلبات",
    "Filter history" => "تصفية السجل",
    "All orders" => "جميع الطلبات",
    "Completed orders" => "الطلبات المكتملة",
    "Pending orders" => "الطلبات المعلقة",
    "Rejected orders" => "الطلبات المرفوضة",
    "View details" => "عرض التفاصيل",
    "Order" => "طلب",
    "Cost" => "التكلفة",
    "Order made on" => "تم الطلب في",
    "Pending" => "قيد الانتظار",
    "Completed" => "مكتمل",
    "Failed" => "فشل",
    "Order Items" => "عناصر الطلب",
    "Close" => "إغلاق",
    "Quantity" => "الكمية",
    "Price" => "السعر",
    "No items found for this order." => "لم يتم العثور على عناصر لهذا الطلب.",
    "No Orders to show." => "لا توجد طلبات لعرضها.",

    // wishlist section
    "Profile" => "الملف الشخصي",
    "Orders" => "الطلبات",
    "Wishlist" => "قائمة الرغبات",
    "Personal Info" => "المعلومات الشخصية",
    "Item removed from wishlist successfully." => "تمت إزالة العنصر من قائمة الرغبات بنجاح.",
    "Failed to remove item from wishlist." => "فشل في إزالة العنصر من قائمة الرغبات.",
    "Wishlist cleared successfully." => "تم مسح قائمة الرغبات بنجاح.",
    "Failed to clear wishlist." => "فشل في مسح قائمة الرغبات.",
    "Product Name" => "اسم المنتج",
    "Clear" => "مسح",
    "Product" => "المنتج",
    "Availability" => "التوفر",
    "Out of Stock" => "غير متوفر",
    "In Stock" => "متوفر",
    "No items to show." => "لا توجد عناصر لعرضها.",
    "clear_items" => "!لا يوجد منتجات لحذفها",

    // process_checkout.php
    "Check-Out" => "الدفع",
    "Please enter a valid PayPal email address." => "يرجى إدخال بريد إلكتروني صالح لـ PayPal.",
    "Please enter a valid 16-digit card number" => "يرجى إدخال رقم بطاقة مكون من 16 رقمًا.",
    "Invalid credit card number" => "رقم البطاقة غير صالح.",
    "Please enter a valid cardholder name" => "يرجى إدخال اسم حامل البطاقة.",
    "Please enter a valid expiry date (MM/YY)" => "يرجى إدخال تاريخ انتهاء صالح (شهر/سنة).",
    "The expiry date has already passed." => "لقد تجاوز تاريخ انتهاء الصلاحية.",
    "Please enter a valid CVV (3 digits)." => "يرجى إدخال رمز CVV صالح (3 أرقام).",
    "Order placed successfully!" => "تم تقديم الطلب بنجاح!",
    "Failed to place order!" => "فشل في تقديم الطلب!",
    "another time" => "مرة أخرى",
    "Pending" => "قيد الانتظار",
    "Payment" => "الدفع",
    "Credit Card" => "بطاقة ائتمان",
    "Card Number" => "رقم البطاقة",
    "Name on card" => "الاسم على البطاقة",
    "Expiry date" => "تاريخ انتهاء الصلاحية",
    "CVV Code" => "رمز CVV",
    "PayPal" => "باي بال",
    "Email address" => "عنوان البريد الإلكتروني",
    "Order Summary" => "ملخص الطلب",
    "Subtotal" => "المجموع الفرعي",
    "Shipping" => "الشحن",
    "Coupon" => "كوبون",
    "Code" => "رمز",
    "TOTAL" => "المجموع",
    "I agree to the" => "أوافق على",
    "terms and conditions" => "الشروط والأحكام",
    "Get emails about product updates and events." => "احصل على تحديثات المنتج والأحداث.",
    "If you change your mind, you can unsubscribe at any time." => "إذا غيرت رأيك، يمكنك إلغاء الاشتراك في أي وقت.",
    "See our policy" => "شاهد سياستنا",
    "Continue to Checkout" => "الاستمرار إلى الدفع",
    "just_one" => "تستطيع اختيار طريقة دفع واحدة فقط",

    // Cart page
    'Home'              => 'الرئيسية',
    'Categories'        => 'الفئات',
    'quantity_positive_integer' => 'يجب أن تكون الكمية عددًا صحيحًا موجبًا.',
    'invalid_quantity' => 'كمية غير صالحة للعنصر ',
    'available' => 'متوفر: ',
    'item_not_found' => 'العنصر غير موجود: ',
    'cart_updated' => 'تم تحديث السلة بنجاح.',
    'item_removed' => 'تمت إزالة العنصر من السلة.',
    'invalid_promo_code' => 'رمز العرض غير صالح.',
    'promo_code_applied' => 'تم تطبيق رمز العرض بنجاح.',
    'empty_cart' => 'سلتك فارغة.',
    'products' => 'المنتجات',
    'continue_shopping' => 'مواصلة التسوق',
    'size' => 'الحجم',
    'color' => 'اللون',
    'you_save' => 'أنت توفر',
    'subtotal' => 'المجموع الفرعي',
    'update_cart' => 'تحديث السلة',
    'remove' => 'إزالة',
    'quantity' => 'الكمية',
    'proceed_to_checkout' => 'الذهاب إلى الدفع',
    'apply_promo_code' => 'تطبيق الكود ',
    'promo_code_placeholder' => 'أدخل الكود',
    'shipping_estimates' => 'تقديرات الشحن',
    'choose_your_country' => 'اختر بلدك',
    'choose_country' => 'يرجى اختيار بلد.',
    'choose_your_city' => 'اختر مدينتك',
    'choose_city' => 'يرجى اختيار مدينة.',
    'zip_postal_code' => 'الرمز البريدي',
    'provide_valid_zip' => 'يرجى تقديم رمز بريدي صالح.',
    'calculate_shipping' => 'احسب تكلفة الشحن',

    // Footer
    'about_us' => 'معلومات عنا',
    'services' => 'الخدمات',
    'terms_condition' => 'الشروط والأحكام',
    'our_blogs' => 'مدوناتنا',
    'help_center' => 'مركز المساعدة',
    'money_refund' => 'استرداد الأموال',
    'terms_policy' => 'الشروط والسياسة',
    'open_dispute' => 'فتح نزاع',
    'user_login' => 'تسجيل دخول المستخدم',
    'user_register' => 'تسجيل مستخدم جديد',
    'account_setting' => 'إعدادات الحساب',
    'my_cart' => 'عربتي',
    'our_app' => 'تطبيقنا',
    'privacy_cookies' => 'الخصوصية والكوكيز',
    'accessibility' => 'إمكانية الوصول',
    'footer_description' => 'في eShop، نقدم لك أحدث الاتجاهات في الموضة والإلكترونيات والسلع المنزلية بأسعار لا تقبل المنافسة. اكتشف عالمًا من المنتجات عالية الجودة وخدمة العملاء الاستثنائية، مما يجعل تجربة تسوقك ممتعة وسلسة.',
    'copyright_text' => '&copy; 2024 eShop جميع الحقوق محفوظة',
    'for_users' => 'للمستخدمين',

    'non-active' => 'لم يتم توثيق حسابك بعد<a href="user-otp.php?resend">وثق الآن</a>',
);
