<?php
$langArray = array(
    'big_file' => 'Your file is too big!',
    'upload_err' => 'There an error while uploadin your file!',
    'type_err' => 'You cannot uploads files of this type!',
    'success_uploads' => 'File uploads successfully',
    'single_file_err' => 'You can select one file only',

    // navbar links
    'Home'              => 'Home',
    'Categories'        => 'Categories',
    'Items'             => 'Items',
    'Profile Settings'  => 'Profile Settings',
    'Logout'            => 'Logout',
    'Sign-in'           => 'Sign-in',
    'Sign-up'           => 'Sign-up',
    'My Profile'        => 'My Profile',
    'Reset password'    => 'Reset password',
    'Wish List'         => 'Wish List',

    // Categories
    'Pet Supplies'      => 'Pet Supplies',
    'Office Supplies'   => 'Office Supplies',
    'Travel'            => 'Travel',
    'Kitchen Appliances' => 'Kitchen Appliances',
    'Computers'         => 'Computers',
    'Video Games'       => 'Video Games',
    'Smart Phones'      => 'Smart Phones',
    'Books'             => 'Books',
    'Automotive'        => 'Automotive',
    'Toys & Games'      => 'Toys & Games',
    'Health & Beauty'   => 'Health & Beauty',
    'Sports'            => 'Sports',
    'Home & Garden'     => 'Home & Garden',
    'Fashion'           => 'Fashion',
    'Electronics'       => 'Electronics',

    // index.php
    'Welcome to ClickCart' => 'Welcome to ClickCart',
    'Your one-stop shop for the best items online. Enjoy our wide selection and fast shipping!' => 'Your one-stop shop for the best items online. Enjoy our wide selection and fast shipping!',
    'Shop now' => 'Shop now',
    'Trending Items' => 'Trending Items',
    'Check out our trending items: PS5, iPhone 16, S24 Ultra, and more!' => 'Check out our trending items: PS5, iPhone 16, S24 Ultra, and more!',
    'Play more<br>today and get' => 'Play more<br>today and get',
    'OFF' => 'OFF',
    'Use code %s to get %s off on Video Games category now' => 'Use code %s to get %s off on Video Games category now',
    'Previous' => 'Previous',
    'Next' => 'Next',
    'Best Sellers' => 'Best Sellers',
    'Most Viewed Items' => 'Most Viewed Items',
    'views' => 'views',

    // items.php
    'results' => 'results',
    'sort_by' => 'Sort by:',
    'featured' => 'Featured',
    'price_low_high' => 'Price: Low to High',
    'price_high_low' => 'Price: High to Low',
    'newest_arrivals' => 'Newest Arrivals',
    'most_viewed' => 'Most Viewed',
    'best_sellers' => 'Best Sellers',
    'previous' => 'Previous',
    'next' => 'Next',
    'first' => 'First',
    'last' => 'Last',
    'item_added_cart' => 'Item added to cart successfully!',
    'item_already_cart' => 'Item is already in your cart.',
    'item_not_found' => 'Item not found.',
    'not_signed_in' => 'You are not signed in to add to cart.',
    'not_signed_in-comment' => 'You must sign in to submit a comment!',
    'comment_submitted' => 'Your comment has been submitted!',
    'comment_empty' => 'Comment cannot be empty!',
    'item_in_wishlist' => 'This Item is already in Your WishList!',
    'item_added_wishlist' => 'Item Added to your WishList!',
    'verified_buyer' => 'You must be a verified buyer to leave a review!',
    'non-approved' => 'This item not Approved yet!',
    'no-items' => 'No items to show!',
    'delete_item_failed' => 'Could not delete the item.',
    'Product_by' => 'Product by',
    'Average_Rate' => 'Average Rate',
    'Based_on' => 'Based on',
    'Ratings' => 'Ratings',
    'customer_reviews' => 'customer reviews',
    '*includes_tax' => '*includes tax',
    'Product_Description' => 'Product Description',
    'Specifications' => 'Specifications',
    'Reviews' => 'Reviews',
    'Description' => 'Description',
    'Write_a_review' => 'Write a review',
    'Rate_this_Item:' => 'Rate this Item:',
    '1star' => '1 Star',
    '2star' => '2 Stars',
    '3star' => '3 Stars',
    '4star' => '4 Stars',
    '5star' => '5 Stars',
    'Submit_Review' => 'Submit Review',
    'posted' => 'Posted',
    'No_comments_available' => 'No comments available',
    'Add_to_cart' => 'Add to cart',
    'Add_to_wishlist' => 'Add to wishlist',
    'Contact_Seller' => 'Contact Seller',
    'no-quantity' => 'Out of Stuck',

    // login.php
    'welcome_back' => 'Welcome Again',
    'login' => 'Login',
    'email_placeholder' => 'Email',
    'email_error_empty' => "Email can't be empty.",
    'email_error_invalid' => "Invalid email format.",
    'password_placeholder' => 'Password',
    'password_error_empty' => "Password can't be empty.",
    'remember_me' => 'Remember Me',
    'login_button' => 'Login',
    'google_login' => 'Continue with Google',
    'forgot_password' => 'Forgot password?',
    'no_account' => "Don't have an account?",
    'sign_up' => 'Sign Up',
    'no_account_with_email' => 'No account found with this email.',
    'incorrect_password' => 'Incorrect password.',

    // register.php
    'signup' => 'Sign Up',
    'welcome' => 'Welcome',
    'first_name' => 'First name',
    'last_name' => 'Last name',
    'password' => 'Password',
    'email' => 'Email',
    'have_account' => 'You have an account?',
    'login' => 'LogIn',
    'register_button' => 'Register',
    'cant_be_empty' => "can't be empty",
    'email_exists' => 'The email you entered already exists!',
    'password_error' => 'Invalid password format.',
    'otp_error' => 'Failed while sending code!',
    'db_error' => 'Something went wrong!',
    'otp_sent' => "We've sent a password reset OTP to your email - ",

    // forgetPass.php
    'password_reset' => 'Password Reset',
    'password_reset_code' => 'Password Reset Code',
    'password_reset_body' => 'Your password reset code is:',
    'otp_sent' => "We've sent a password reset OTP to your email",
    'mail_error' => "Message couldn't be sent. Mail error",
    'something_went_wrong' => 'Something went wrong!',
    'email_not_exist' => 'This email address does not exist!',
    'password_reset_instructions' => 'Provide the email address associated with your account to recover your password.',
    'reset_password_button' => 'Reset Password',
    'email' => 'Email',
    'login' => 'Login',
    'register' => 'Register',

    // reset-code.php
    'code_verification' => 'Code Verification',
    'no_email_session' => 'Please log in first.',
    'create_new_password_info' => 'Please create a new password that you don\'t use on any other site.',
    'incorrect_code' => 'You\'ve entered an incorrect code!',
    'email_verification_code' => 'Email Verification Code',
    'new_code' => 'Your new verification code is:',
    'new_verification_code_sent' => 'A new verification code has been sent to your email.',
    'failed_to_send_new_code' => 'Failed while sending new code!',
    'failed_to_update_code' => 'Failed to update the code in the database!',
    'verify' => 'Verify',
    'code_sent' => 'Your code was sent to you via email',
    'did_not_receive_code' => 'Didn\'t receive the code? Request again',
    'verify_button' => 'Verify',

    // new-password.php
    'reset_password' => 'Reset Password',
    'cannot_be_empty' => "Can't be empty",
    'passwords_not_matching' => 'Confirm password does not match!',
    'password_changed' => 'Your password has been changed.',
    'strong_password_info' => 'Strong passwords include numbers, letters, and punctuation marks.',
    'new_password_info' => 'Your password has been changed. Now you can log in with your new password.',
    'reset_password_button' => 'Reset Password',
    'reset_password_header' => 'Reset Your Password',
    'password_placeholder' => 'Enter password',
    'confirm_password_placeholder' => 'Confirm new password',
    'db_error' => 'Failed to change your password!',

    // user-otp.php
    'pageTitle' => 'Verification Code',
    'redirectToLogin' => 'Please log in.',
    'otpInstructions' => 'Your code was sent to you via email',
    'otpIncorrect' => 'You\'ve entered an incorrect code!',
    'otpErrorUpdate' => 'Failed while updating code!',
    'otpErrorResend' => 'Failed while sending new code!',
    'otpResent' => 'A new verification code has been sent to your email.',
    'otpUpdatedSuccess' => 'Registered successfully!',
    'verify' => 'Verify',
    'verifyPrompt' => 'Your code was sent to you via email',
    'verifyButton' => 'Verify',
    'resend' => 'Didn\'t receive the code? Request again',

    // newAd.php (Add section)
    'New Ad' => 'New Ad',
    'Product already exists' => 'Product already exists',
    'Price cannot be less than 0.99' => 'Price cannot be less than 0.99',
    'Quantity cannot be less than 1' => 'Quantity cannot be less than 1',
    'Select the item status' => 'Select the item status',
    'Select a category' => 'Select a category',
    'Add New Product' => 'Add New Product',
    'Product Picture' => 'Product Picture',
    'JPG or PNG, max size 5 MB' => 'JPG or PNG, max size 5 MB',
    'Upload' => 'Upload',
    'Product Details' => 'Product Details',
    'Product added successfully' => 'Product added successfully wait for Aproval',
    'No changes were made' => 'No changes were made',
    'Product Name' => 'Product Name',
    'Name of The Item' => 'Name of The Item',
    'Selling Price' => 'Selling Price',
    'Price of The Item' => 'Price of The Item',
    'Country Made' => 'Country Made',
    'Country of Origin' => 'Country of Origin',
    'Quantity' => 'Quantity',
    'Quantity of The Item' => 'Quantity of The Item',
    'Product Status' => 'Product Status',
    'Select Product Status' => 'Select Product Status',
    'New' => 'New',
    'Like New' => 'Like New',
    'Used' => 'Used',
    'Very Old' => 'Very Old',
    'Category' => 'Category',
    'Select Category' => 'Select Category',
    'Description' => 'Description',
    'Description of The Item' => 'Description of The Item',
    'Add Item' => 'Add Item',
    'Primary Image' => 'Primary Image',
    'Additional Image 1' => 'Additional Image 1',
    'Additional Image 2' => 'Additional Image 2',

    // newAd.php (Edit section)
    'Edit Product' => 'Edit your Item',
    'Edit Item' => 'Edit item',
    'delete-item' => 'delete item',
    'Product Updated successfully' => 'Product Updated successfully wait for Aproval',
    'Are you sure to delete?' => 'Are you sure to delete?',
    'success_delete' => 'Deleted Succefully',
    'item_not_provided' => 'Item ID not provided.',

    // profile-settings.php
    'profile' => 'Profile',
    'orders' => 'Orders',
    'wishlist' => 'Wishlist',
    'personal_info' => 'Personal Info',
    'first_name' => 'First name',
    'enter_first_name' => 'Enter your Firstname',
    'last_name' => 'Last name',
    'enter_last_name' => 'Enter your Lastname',
    'location' => 'Location',
    'enter_location' => 'Enter your location',
    'gender' => 'Gender',
    'select_gender' => 'Select Your Gender',
    'male' => 'Male',
    'female' => 'Female',
    'email_address' => 'Email address',
    'enter_email' => 'Enter your email address',
    'phone' => 'Phone number',
    'enter_phone' => 'Enter your phone number',
    'birthday' => 'Birthday',
    'enter_birthday' => 'Enter your birthday',
    'upload' => 'Upload',
    'profile_picture' => 'Profile Picture',
    'picture_info' => 'JPG or PNG no larger than 5 MB',
    'account_details' => 'Account Details',
    'save_changes' => 'Save changes',
    'success_update' => 'Member updated successfully!',
    'warning_no_changes' => 'No changes were made. No record updated.',

    // info section
    "Profile" => "Profile",
    "Orders" => "Orders",
    "Wishlist" => "Wishlist",
    "Personal Info" => "Personal Info",
    "My Profile" => "My Profile",
    "My Ads" => "My Ads",
    "New Ad?" => "New Ad?",
    "Approved" => "Approved",
    "Waiting Approval" => "Waiting Approval",
    "No Ads to Show. Create" => "No Ads to Show. Create",
    "New Ad" => "New Ad",
    "My Latest Comments" => "My Latest Comments",
    "Commented on:" => "Commented on:",
    "Item:" => "Item:",
    "No comments to show." => "No comments to show.",
    'edit-item'=> 'Edit item',

    // orders section
    "Profile" => "Profile",
    "Orders" => "Orders",
    "Wishlist" => "Wishlist",
    "Personal Info" => "Personal Info",
    "Order history" => "Order history",
    "Filter history" => "Filter history",
    "All orders" => "All orders",
    "Completed orders" => "Completed orders",
    "Pending orders" => "Pending orders",
    "Rejected orders" => "Rejected orders",
    "View details" => "View details",
    "Order" => "Order",
    "Cost" => "Cost",
    "Order made on" => "Order made on",
    "Pending" => "Pending",
    "Completed" => "Completed",
    "Failed" => "Failed",
    "Order Items" => "Order Items",
    "Close" => "Close",
    "Quantity" => "Quantity",
    "Price" => "Price",
    "No items found for this order." => "No items found for this order.",
    "No Orders to show." => "No Orders to show.",

    // wishlist section
    "Profile" => "Profile",
    "Orders" => "Orders",
    "Wishlist" => "Wishlist",
    "Personal Info" => "Personal Info",
    "Item removed from wishlist successfully." => "Item removed from wishlist successfully.",
    "Failed to remove item from wishlist." => "Failed to remove item from wishlist.",
    "Wishlist cleared successfully." => "Wishlist cleared successfully.",
    "Failed to clear wishlist." => "Failed to clear wishlist.",
    "Product Name" => "Product Name",
    "Clear" => "Clear",
    "Product" => "Product",
    "Availability" => "Availability",
    "Out of Stock" => "Out of Stock",
    "In Stock" => "In Stock",
    "No items to show." => "No items to show.",
    "clear_items" => "There is no items to clear!",

    // process_checkout.php
    "Check-Out" => "Check-Out",
    "Please enter a valid PayPal email address." => "Please enter a valid PayPal email address.",
    "Please enter a valid 16-digit card number" => "Please enter a valid 16-digit card number",
    "Invalid credit card number" => "Invalid credit card number",
    "Please enter a valid cardholder name" => "Please enter a valid cardholder name",
    "Please enter a valid expiry date (MM/YY)" => "Please enter a valid expiry date (MM/YY)",
    "The expiry date has already passed." => "The expiry date has already passed.",
    "Please enter a valid CVV (3 digits)." => "Please enter a valid CVV (3 digits).",
    "Order placed successfully!" => "Order placed successfully!",
    "Failed to place order!" => "Failed to place order!",
    "another time" => "another time",
    "Pending" => "Pending",
    "Payment" => "Payment",
    "Credit Card" => "Credit Card",
    "Card Number" => "Card Number",
    "Name on card" => "Name on card",
    "Expiry date" => "Expiry date",
    "CVV Code" => "CVV Code",
    "PayPal" => "PayPal",
    "Email address" => "Email address",
    "Order Summary" => "Order Summary",
    "Subtotal" => "Subtotal",
    "Shipping" => "Shipping",
    "Coupon" => "Coupon",
    "Code" => "Code",
    "TOTAL" => "TOTAL",
    "I agree to the" => "I agree to the",
    "terms and conditions" => "terms and conditions",
    "Get emails about product updates and events." => "Get emails about product updates and events.",
    "If you change your mind, you can unsubscribe at any time." => "If you change your mind, you can unsubscribe at any time.",
    "See our policy" => "See our policy",
    "Continue to Checkout" => "Continue to Checkout",
    "just_one" => "You can choose only one payment method",

    // Cart page
    'quantity_positive_integer' => 'Quantity must be a positive integer.',
    'invalid_quantity' => 'Invalid quantity for item ',
    'available' => 'Available: ',
    'item_not_found' => 'Item not found: ',
    'cart_updated' => 'Cart updated successfully.',
    'item_removed' => 'Item removed from cart.',
    'invalid_promo_code' => 'Invalid promo code.',
    'promo_code_applied' => 'Promo code applied successfully.',
    'empty_cart' => 'Your cart is empty.',
    'products' => 'Products',
    'continue_shopping' => 'Continue Shopping',
    'size' => 'Size',
    'color' => 'Color',
    'you_save' => 'You save',
    'subtotal' => 'Subtotal',
    'update_cart' => 'Update Cart',
    'remove' => 'Remove',
    'quantity' => 'Quantity',
    'proceed_to_checkout' => 'Proceed to Checkout',
    'apply_promo_code' => 'Apply Promo Code',
    'promo_code_placeholder' => 'Enter promo code here',
    'shipping_estimates' => 'Shipping Estimates',
    'choose_your_country' => 'Choose Your Country',
    'choose_country' => 'Please choose a country.',
    'choose_your_city' => 'Choose Your City',
    'choose_city' => 'Please choose a city.',
    'zip_postal_code' => 'Zip/Postal Code',
    'provide_valid_zip' => 'Please provide a valid zip/postal code.',
    'calculate_shipping' => 'Calculate Shipping',

    // Footer
    'about_us' => 'About us',
    'services' => 'Services',
    'terms_condition' => 'Terms & Condition',
    'our_blogs' => 'Our Blogs',
    'help_center' => 'Help center',
    'money_refund' => 'Money refund',
    'terms_policy' => 'Terms and Policy',
    'open_dispute' => 'Open dispute',
    'user_login' => 'User Login',
    'user_register' => 'User Register',
    'account_setting' => 'Account Setting',
    'my_cart' => 'My Cart',
    'our_app' => 'Our app',
    'privacy_cookies' => 'Privacy & Cookies',
    'accessibility' => 'Accessibility',
    'footer_description' => 'At eShop, we bring you the latest trends in fashion, electronics, and home goods—all at unbeatable prices. Discover a world of quality products and exceptional customer service, making your shopping experience enjoyable and seamless.',
    'copyright_text' => '&copy; 2024 eShop All rights reserved',
    'for_users' => 'For users',

    'non-active' => 'Your non Verified yet<a href="user-otp.php?resend">Verify now</a>'
);
